# 시퀀스

## 2.2 지능형 리스트와 제너레이터 표현식

### 2.2.1 지능형 리스트와 가독성

In [1]:
# 예제 2-1 문자열에서 유니코드 코드포인트 리스트 만들기(버전 1)
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

codes

[36, 162, 163, 165, 8364, 164]

In [2]:
# 예제 2-2 문자열에서 유니코드 코드포인트 리스트 만들기 (버전 2)
symbols = '$¢£¥€¤'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

In [3]:
# 파이썬 3 버전에서 for문에서 사용된 변수는 처음 설정되었던 값을 건드리지 않는다
x = 'ABC'
dummy = [ord(x) for x in x]
print(x) # x의 값이 유지된다
print(dummy) # 지능형 리스트도 제대로 작동한다

ABC
[65, 66, 67]


### 2.2.2 지능형 리스트와 map()/filter() 비교

In [4]:
# 예제 2-3 지능형 리스트와 맵/필터 구성으로 만든 동일 리스트
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print(beyond_ascii)

beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols))) # map, filter 조합이 더 빠르지 않다
print(beyond_ascii)

[162, 163, 165, 8364, 164]
[162, 163, 165, 8364, 164]


### 2.2.3 데카르트 곱

In [5]:
# 예제 2-4 지능형 리스트를 이용한 데카르트 곱
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes] # color 다음에 size를 배치해서 만든 튜플 리스트
print(tshirts)

for color in colors: # color를 반복하는 루프 안에서 sizes를 반복해서 튜플 리스트 생성
    for size in sizes:
        print((color, size))

tshirts = [(color, size) for size in sizes # size 다음에 color를 배치해서 만든 튜플 리스트
                         for color in colors]
print(tshirts)

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')
[('black', 'S'), ('white', 'S'), ('black', 'M'), ('white', 'M'), ('black', 'L'), ('white', 'L')]


In [6]:
# 예제 1-1의 예시
import collections

Card = collections.namedtuple('Card', ['rank', 'suit'])

class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)] + list('JQKA')
    suits = 'spades diamonds clubs hearts'.split()

    def __init__(self):
        # 다음 코드를 이용해서 13가지 순위와 4가지 종류로 구성된 52장의 카드 한 벌을 초기화
        self._cards = [Card(rank, suit) for suit in self.suits
                                       for rank in self.ranks]

    def  __len__(self):
        return len(self._cards)

    def __getitem__(self, position):
        return self._cards[position]

In [7]:
# 예제 2-5 제너레이터 표현식에서 튜플과 배열 초기화하기
symbols = '$¢£¥€¤'
# 제너레이터 표현식이 함수에 보내는 단 하나의 인수라면 괄호 안에 또 괄호를 넣을 필요는 없다
print(tuple(ord(symbol) for symbol in symbols)) 

import array

# 배열 생성자는 인수를 두개 받으므로 제너레이터 표현식 앞뒤에 반드시 괄호를 넣어야 한다 (배열 생성자의 첫 번째 인수는 저장할 자료형을 지정한다)
print(array.array('I', (ord(symbol) for symbol in symbols)))

(36, 162, 163, 165, 8364, 164)
array('I', [36, 162, 163, 165, 8364, 164])


In [8]:
# 예제 2-6 제너레이터 표현식에서의 데카르트 곱
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
# 제너레이터 표현식은 한번에 하나의 항목을 생성한다. 리스트는 생성하지 않는다
for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes): 
    print(tshirt)

black S
black M
black L
white S
white M
white L


## 2.3 튜플은 단순한 불변 리스트가 아니다

### 2.3.1 레코드로서의 튜플

In [9]:
# 예제 2-7 레코드로 사용된 튜플
lax_coordinates = (33.9425, -118.408056) # LA 국제공항의 위도, 경도
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014) # 지명, 년도, 백만 단위 인구수, 인구 변화율, 제곱킬로미터 단위 면적
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), # 국가코드, 여권 번호
                ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids): # 리스트를 반복할 때 passport 변수가 각 튜플에 바인딩 됨
    print('%s/%s' % passport)

for country, _ in traveler_ids: # 두 번째 항목에는 관심이 없으므로 더미 변수를 나타내는 _를 활용
    print(country)

BRA/CE342567
ESP/XDA205856
USA/31195855
USA
BRA
ESP


### 2.3.2 튜플 언패킹

In [10]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates # 튜플 언패킹
latitude
longitude

-118.408056

In [11]:
a = 1
b = 2
# 튜플 언패킹을 사용하면 임시 변수를 사용하지 않고도 두 변수의 값을 교환할 수 있다
a, b = b, a
print(f'a: {a}, b: {b}')

a: 2, b: 1


In [12]:
print(divmod(20, 8))

t = (20, 8)
print(divmod(*t)) # 함수를 호출할 때 인수 앞에 *을 붙혀 튜플을 언패킹할 수 있다

quotient, remainder = divmod(*t)
print((quotient, remainder))

(2, 4)
(2, 4)
(2, 4)


In [13]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub') # _: 플레이스 홀더
print(filename)

idrsa.pub


In [14]:
# 함수 매개변수에 *를 사용해서 초과된 인수를 가져올 수 있다
a, b, *rest = range(5)
print(a, b, rest)

a, b, *rest = range(3)
print(a, b, rest)

a, b, *rest = range(2)
print(a, b, rest)

0 1 [2, 3, 4]
0 1 [2]
0 1 []


In [15]:
# 병렬 할당의 경우 *는 한 가지의 변수에만 사용이 가능하다
a, *body, c, d = range(5)
print(a, body, c, d)

*head, b, c, d = range(5)
print(head, b, c, d)

0 [1, 2] 3 4
[0, 1] 2 3 4


### 2.3.3 내포된 튜플 언패킹

In [16]:
# 예제 2-8 longitude에 접근하기 위해 내포된 튜플 언패킹하기
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)), # 마지막 필드는 좌표쌍
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'Br', 19.649, (-23.547778, -46.635833)),
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:^9.4f} | {:^9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas: # 마지막 필드를 튜플에 할당함으로써 좌표를 언패킹한다
    if longitude <= 0: # 경도가 음수인 서반구 도시만 출력
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |  19.4333  | -99.1333 
New York-Newark |  40.8086  | -74.0204 
Sao Paulo       | -23.5478  | -46.6358 


### 2.3.4 명명된 튜플

In [17]:
# 예제 1-1의 예시
import collections

# 예제 1-1 에서 Card 클래스를 정의한 방법
Card = collections.namedtuple('Card', ['rank', 'suit'])

class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)] + list('JQKA')
    suits = 'spades diamonds clubs hearts'.split()

    def __init__(self):
        self._cards = [Card(rank, suit) for suit in self.suits
                                       for rank in self.ranks]

    def  __len__(self):
        return len(self._cards)

    def __getitem__(self, position):
        return self._cards[position]

In [18]:
# 예제 2-9 명명된 튜플형을 정의하고 사용하기
from collections import namedtuple
# 명명된 튜플을 정의하려면 클래스명, 필드명의 리스트(반복형 문자열 or 공백으로 구분된 하나의 문자열) 등 총 두개의 매개변수가 필요하다
City = namedtuple('City', 'name country population coordicates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667)) # 데이터는 위치를 맞추고 콤바로 구분해서 생성자에 전달해야 한다
print(tokyo)

print(tokyo.population) # 필드명을 이용해서 필드에 접근

print(tokyo[1]) # 위치를 이용해서 필드에 접근

City(name='Tokyo', country='JP', population=36.933, coordicates=(35.689722, 139.691667))
36.933
JP


In [19]:
# 예제 2-10 명명된 튜플의 속성과 메서드
print(City._fields) # _fields는 클래스의 필드명을 담고 있는 튜플
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data) # _make()는 반복형 객체로부터 명명된 튜플을 만든다. City(*delhi_data)를 호출하는 코드와 동일한 역할을 수행
print(delhi._asdict()) # _asdict()는 명된 튜플 객체에서 만들어진 collections.OrderedDict 객체를 반환한다
for key, value in delhi._asdict().items():
    print(key + ':', value)

('name', 'country', 'population', 'coordicates')
OrderedDict([('name', 'Delhi NCR'), ('country', 'IN'), ('population', 21.935), ('coordicates', LatLong(lat=28.613889, long=77.208889))])
name: Delhi NCR
country: IN
population: 21.935
coordicates: LatLong(lat=28.613889, long=77.208889)


## 2.4 슬라이싱

### 2.4.1 슬라이스와 범위 지정시에 마지막 항목이 포함되지 않는 이유

In [20]:
"""
1. range(3), my_list[:3] 처럼 중단점만 이용할 때 길이를 계산하기 쉽다
2. 시작점과 중단점을 모두 지정할 때도 길이 계산이 쉽다 (중단점 - 시작점)
3. 아래 예제처럼 x인덱를 기준으로 겹침 없이 시퀀스를 분할하기 쉽다
"""
l = [10, 20, 30, 40, 50, 60]
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])

[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


### 2.4.2 슬라이스 객체

In [21]:
"""
s[a:b:c]는 c 보폭만큼씩 항목을 건너뛰는 것
"""
s = 'bicycle'
print(s[::3])
print(s[::-1])
print(s[::-2])

bye
elcycib
eccb


In [22]:
# 1장에서는 이런식으로 Ace카드만 추려내는데 사용
deck = FrenchDeck()
print(deck[12::13])

[Card(rank='A', suit='spades'), Card(rank='A', suit='diamonds'), Card(rank='A', suit='clubs'), Card(rank='A', suit='hearts')]


In [23]:
# 예제 2-11 단순 텍스트 파일 청구서의 행 항목들
"""
각 슬라이스에 이름을 붙이면 가독성이 좋아진다
"""

invoice = """
0.....6.................................40........52..55........
1909  Pimoroni PiBrella                     $17.70   3    $52.50
1489  6mm Tactile Switch x20                 $4.95   2     $9.90
1510  Panavise Jr. - PV-201                 $28.00   1    $28.00
1601  PiTFT Mini Kit 320x240                $24.95   1    $34.95
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
ITEM_TOTAL = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.70   Pimoroni PiBrella                 
     $4.95   6mm Tactile Switch x20            
    $28.00   Panavise Jr. - PV-201             
    $24.95   PiTFT Mini Kit 320x240            
 


### 2.4.3 다차원 슬라이싱과 생략 기호

생략 기호 객체는 f(a, ..., z)처럼 함수의 인수나, a[i:...]처럼 슬라이스의한 부분으로 전달할 수 있다.    
numpy에서는 x[i, ...]처럼 사용 (x[i, :, :, :,]와 동일])

### 2.4.4 슬라이스에 할당하기

In [24]:
l = list(range(10))
print(l)
l[2:5] = [20, 30]
print(l)
del l[5:7]
print(l)
l[3::2] = [11, 12]
print(l)

"""
l[2:5] = 100
TypeError: can only assign an iterable
"""

l[2:5] = [100]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 12, 9]
[0, 1, 100, 12, 9]


## 2.5 시퀀스에 덧셈과 곱셈 연산자 사용하기



In [25]:
l = [1, 2, 3]
print(l * 5)

print(5 * 'abcd')

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
abcdabcdabcdabcdabcd


### 2.5.1 리스트의 리스트 만들기

In [26]:
# 예제 2-12 길이가 3인 리스트 3개로 표현한 틱택토 보드
board = [['_'] * 3 for i in range(3)] # 항목 3개를 가진 리스트 세 개를 담은 리스트 생성
print(board)

board[1][2] = 'X' # 1열 2행 을 'X'로 변경
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [27]:
# 예제 2-13 동일한 리스트에 대한 3개의 참조를 가진 리스트는 쓸모없다
weird_board = [['_'] * 3] * 3 # 최상위 리스트가 동일한 내부 리스트에 대한 참조 3개를 가짐 문제가 없는 것 처럼 보인다
print(weird_board)

weird_board[1][2] = 'O' # 1행 2열만 변경했지만 모든 열 2행이 바뀜
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


예제 2-13에서는 세 리스트 모두 같은 리스트를 참조하기 때문에 한번에 바뀌므로 예제 2-12처럼 지능형 리스트를 사용하는것이 좋다

In [28]:
# 예제 2-13 코드의 작동 방식
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row) # 동일한 행이 board 리스트에 세 번 추가된다

print(board)
board[2][0] = 'X'
print(board) # 의도한 바와 다르게 모든 0열이 변경됨

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['X', '_', '_'], ['X', '_', '_'], ['X', '_', '_']]


In [29]:
# 예제 2-12 코드의 작동 방식
board = []
for i in  range(3):
    row = ['_'] * 3 # 반복할 때 마다 row 객체를 새로 만들어 추가
    board.append(row)

print(board)
board[2][0] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]


## 2.6 시퀀스의 복합 할당

\>>> a += b   
위 예시에서 a에 \__iadd__() 매서드를 구현하지 않은 경우, a += b를 a = a + b로 계산하여 a + b를 계산한 뒤 객체를 새로 생성한 후 a에 할당한다   
(\__iadd__()에서 i는 in-place를 의미한다)

In [30]:
l = [1, 2, 3]
print(f'초기 리스트의 id : {id(l)}')

l *= 2 # l = [1, 2, 3, 1, 2, 3]
print(f'곱셈 연산을 수행한 후 리스트의 id : {id(l)}')

t = (1, 2, 3)
print(f'초기 튜플의 id : {id(t)}')

t *= 2
print(f'연산을 수행한 후 튜플의 id : {id(t)}')

초기 리스트의 id : 139751163356488
곱셈 연산을 수행한 후 리스트의 id : 139751163356488
초기 튜플의 id : 139751163383168
연산을 수행한 후 튜플의 id : 139751163501832


### 2.6.1 += 복합 할당 퀴즈

\# 예제 2-14 퀴즈    
아래의 코드를 실행시켜보지 말고 풀어보자   

```
\>>> t = (1, 2, [30, 40])   
\>>> t[2] += [50, 60]   
```

a. t는 (1, 2 [30, 40, 50, 60]이 된다    
b. '튜플 객체는 항목할당을 지원하지 않는다'는 메세지와 함께 TypeError가 발생한다     
c. a와 b 둘 다 틀리다    
d. a와 b 둘 다 맞다     

In [31]:
# 예제 2-15 예상치 못한 결과 (에러가)

# t = (1, 2, [30, 40])
# t[2] += [50, 60]
# print(t)

# 에러를 없애기 위해 위 코드를 수정하였다.
t = (1, 2, [30, 40])
try:
    t[2] += [50, 60] # TypeError: 'tuple' object does not support item assignment
except:
    print("TypeError: 'tuple' object does not support item assignment")
    
print(t)

TypeError: 'tuple' object does not support item assignment
(1, 2, [30, 40, 50, 60])


=> 나는 b가 정답일 것 이라고 예상했다. 에러가 날거라고는 예상을 했는데 에러가 나면서 값이 바뀔줄은 몰랐다.   
[파이썬 튜터 사이트](http://www.pythontutor.com/)에서 작동 원리를 확인해보자

In [32]:
# extend를 이용하면 에러가 발생하지 않음
t = (1, 2, [30, 40])
t[2].extend([50, 60])
print(t)

(1, 2, [30, 40, 50, 60])


In [33]:
# 예제 2-16 s[a] += b 표현식에 대한 바이트코드
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


6 BINARY_SUBSCR # s[a]값을 스택의 꼭대기(Top Of Stack : TOS)에 놓는다   
10 INPLACE_ADD # TOS += b 연산을 수행한다 TOS가 가변객체이면 이 연산은 성공   
14 STORE_SUBSCR # TOS를 s[a]에 할당한다 s가 불변 객체이면 이 연산은 실패한다

## 2.7 list.sort()와 sorted() 내장 함수

In [34]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted(fruits)) # 알파벳순으로 정렬된 문자열들을 담은 새로운 리스트를 생성
print(fruits) # 기존의 리스트는 바뀌지 않음
print(sorted(fruits, reverse=True)) # 알파벳 역순으로 정렬
print(sorted(fruits, key=len)) # 길이 순서로 정렬, 같은 길이인 grape와 apple의 순서는 유지
print(sorted(fruits, key=len, reverse=True)) # 길이 역순으로 정렬, grape와 apple의 순서가 유지되었으므로, 위의 list의 역수와 다르다
print(fruits) # 기존의 리스트는 바뀌지 않음
fruits.sort() # 리스트를 정렬하고 None을 반환
print(fruits) # fruits리스트가 정렬됨

['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']
['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']
['raspberry', 'banana', 'grape', 'apple']
['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']


## 2.8 정렬된 시퀀스를 bisect로 관리하기

In [35]:
# 예제 2-17 정렬된 시퀀스에서 항목을 추가할 위치를 찾아내는 bisect
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 3, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position= bisect_fn(HAYSTACK, needle) # 간격 위치를 찾아내기 위한 bisect 함수를 사용한다
        offset = position * '  |' # 간격을 맞춰서 막대 만들기
        print(ROW_FMT.format(needle, position, offset)) # 막대와 삽입 위치를 보여주는 행을 출력
        
if __name__ == '__main__':
    if input('left? or right? : ') == 'left': # 마지막 명령행 인수에 따라 사용할 bisect 함수를 선택한다
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
    
    print('DEMO:', bisect_fn.__name__) # 선택된 함수명을 헤더에 출력
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO: bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 3 @  1      |3 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [36]:
# 예제 2-18 시험 점수를 입력받아 등급 문자를 반환하는 grade()함수
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

### 2.8.2 bisect.insort()로 삽입하기

In [37]:
# 예제 2-19 시퀀스를 항상 정렬된 상태로 유지하는 insort
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


## 2.9 리스트가 답이 아닐 때

### 2.9.1 배열

In [38]:
# 예제 2-20 커다란 실수 배열의 생성, 저장, 로딩
from array import array # array형을 임포트힌다
from random import random
floats = array('d', (random() for i in range(10**7))) # 반복 가능한 객체에서 배밀도 실수('d').의 배열을 생성한다
print(floats[-1]) # 배열의 마지막 숫자를 조사한다
fp = open('floats.bin', 'wb')
floats.tofile(fp) # 배열을 이진 파일에 저장한다
fp.close()
floats2 = array('d') # 비어있는 배밀도 실수 배열을 생성한다
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7) # 이진 파일에서 천만 개의 숫자를 읽어온다
fp.close()
print(floats2[-1]) # 배열의 마지막 숫자를 조사한다
print(floats2 == floats) # 배열의 내용이 일치하는지 확인한다

0.5963321947530882
0.5963321947530882
True


In [39]:
# array형에는 list.sort()처럼 배열을 직접 변경하는 매서드가 없어 아래처럼 배열을 다시 만들어야 한다
floats = array('d', (random() for i in range(10)))
print(floats)
floats = array(floats.typecode, sorted(floats))
print(floats)

array('d', [0.7413197791451314, 0.7089270853540668, 0.8652059623922853, 0.6545775128269232, 0.25558368805863596, 0.622443363053152, 0.22861055235612937, 0.37557510466167965, 0.9808377306597083, 0.20540746691872136])
array('d', [0.20540746691872136, 0.22861055235612937, 0.25558368805863596, 0.37557510466167965, 0.622443363053152, 0.6545775128269232, 0.7089270853540668, 0.7413197791451314, 0.8652059623922853, 0.9808377306597083])


### 2.9.2 메모리 뷰

In [40]:
# 예제 2-21 배열 값의 바이트 중 하나를 변경하기
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers) # 짧은 정수('h') 다섯개가 있는 배열에서 memoryview 객체를 만든다
print(len(memv))

print(memv[0]) # memv도 배열 안에 있는 5개의 항목을 동일하게 본다

memv_oct = memv.cast('B') # memv 요소를 unsigned char('B')로 형변환한 memv_oct를 생성
print(memv_oct.tolist()) # 값을 조사하기 위해 memv_oct 안의 요소를 리스트로 만든다

memv_oct[5] = 4 # 5번 인덱스에 4를 할당한다
print(numbers) # unsigned int의 최상위 바이트에서 4는 1024에 해당한다

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


In [41]:
# 예제 2-22 numpy.ndarray에서 행과 열을 이용한 기본 연산
import numpy as np # numpy 임포트
a = np.arange(12) # 0 ~ 11의 정수를 담은 numpy.ndarray를 생성
print(a)
print(type(a))
print(a.shape) # 배열의 차원을 살펴본다 (12,) : 12개의 요소를 가진 1차원 배열

a.shape = 3, 4 # 3행 4열의 배열로 변경
print(a)

print(a[2]) # 2번 행을 가져온다
print(a[2, 1]) # 2행 1열의 요소를 가져온다 (실제 행렬 기반에선 3행 2열)
print(a[:, 1]) # 1번 열을 가져온다
print(a.transpose()) # 새로운 배열인 전치 행렬을 반환한다

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 2.9.4 덱 및 기타 큐
dequq는 양쪽 끝에 추가나 제거하는 연산에 최적화되어있다

In [42]:
# 예제 2-23 덱 이용하기
from collections import deque
dq = deque(range(10), maxlen=10) # maxlen은 deque 객체가 수용할 수 있는 최대 항목 수
print(dq)
dq.rotate(3) # rotate() 매서드는 받은 인수만큼 항목을 이동시킨다
print(dq)
dq.rotate(-4)
print(dq)
dq.appendleft(-1) # 왼쪽에 항목을 추가한다 가득 찬 경우엔 오른쪽에 있는 항목들이 먼저 밀려남
print(dq)
dq.extend([11, 22, 33]) # 오른쪽에 항목 추가
print(dq)
dq.extendleft([10, 20, 30, 40]) # 항목이 역순으로 추가
print(dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)


뒷 이야기   
혼합된 자료형 리스트

In [43]:
# 리스트 안에 여러 자료형이 들어있으므로 정렬이 불가하다
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19]

try:
    sorted(l)
except TypeError:
  print("TypeError: '<' not supported between instances of 'str' and 'int'")

TypeError: '<' not supported between instances of 'str' and 'int'


key는 훌륭하다

In [44]:
# key를 사용하면 숫자와 숫자 형태의 문자열로 구성된 리스트도 정렬이 가능하다
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19]
print(sorted(l, key=int))
print(sorted(l, key=str))

[0, '1', 5, 6, '9', 14, 19, '23', 28, '28']
[0, '1', 14, 19, '23', 28, '28', 5, 6, '9']
